### Loading data from clouderizer drive

In [35]:
!ln -s ../data/ ./
!ln -s ../out/ ./

ln: failed to create symbolic link './data': File exists
ln: failed to create symbolic link './out': File exists


### Importing useful library

In [1]:
import os
import pandas as pd
import numpy as np
from keras.preprocessing import image

Using TensorFlow backend.


In [5]:
# Convolutional Neural Network


# Part 1 - Building the CNN

# Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense

# Initialising the CNN
classifier = Sequential()

# Step 1 - Convolution
classifier.add(Conv2D(32, (3, 3), input_shape = (64, 64, 3), activation = 'relu'))

# Step 2 - Pooling
classifier.add(MaxPooling2D(pool_size = (2, 2)))

# Adding a second convolutional layer
classifier.add(Conv2D(32, (3, 3), activation = 'relu'))
classifier.add(MaxPooling2D(pool_size = (2, 2)))

classifier.add(Conv2D(32, (3, 3), activation = 'relu'))
classifier.add(MaxPooling2D(pool_size = (2, 2)))

# Step 3 - Flattening
classifier.add(Flatten())

# Step 4 - Full connection
classifier.add(Dense(units = 128, activation = 'relu'))
classifier.add(Dense(units = 12, activation = 'softmax'))

# Compiling the CNN
classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Part 2 - Fitting the CNN to the images

from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)

test_datagen = ImageDataGenerator(rescale = 1./255)

training_set = train_datagen.flow_from_directory('data/training',
                                                 target_size = (64, 64),
                                                 batch_size = 32,
                                                 class_mode = 'categorical')

test_set = test_datagen.flow_from_directory('data/validation',
                                            target_size = (64, 64),
                                            batch_size = 32,
                                            class_mode = 'categorical')

classifier.fit_generator(training_set,
                         steps_per_epoch = 8000,
                         epochs = 25,
                         validation_data = test_set,
                         validation_steps = 2000)



Found 4674 images belonging to 12 classes.
Found 759 images belonging to 12 classes.
Epoch 1/25
8000/8000 [==============================] - 706s 88ms/step - loss: 0.7059 - acc: 0.7660 - val_loss: 2.7924 - val_acc: 0.5523
Epoch 2/25
8000/8000 [==============================] - 737s 92ms/step - loss: 0.1597 - acc: 0.9480 - val_loss: 3.3653 - val_acc: 0.5560
Epoch 3/25
8000/8000 [==============================] - 743s 93ms/step - loss: 0.1016 - acc: 0.9677 - val_loss: 4.0814 - val_acc: 0.5322
Epoch 4/25
8000/8000 [==============================] - 741s 93ms/step - loss: 0.0799 - acc: 0.9743 - val_loss: 4.2046 - val_acc: 0.5191
Epoch 5/25
8000/8000 [==============================] - 745s 93ms/step - loss: 0.0692 - acc: 0.9783 - val_loss: 4.0981 - val_acc: 0.5586
Epoch 6/25
8000/8000 [==============================] - 760s 95ms/step - loss: 0.0629 - acc: 0.9799 - val_loss: 4.2283 - val_acc: 0.5692
Epoch 7/25
8000/8000 [==============================] - 769s 96ms/step - loss: 0.0553 - acc: 

### Checking the indices for each class 

In [6]:
training_set.class_indices

{'Ant-Man': 0,
 'Aquaman': 1,
 'Avengers': 2,
 'Batman': 3,
 'Black Panther': 4,
 'Captain America': 5,
 'Catwoman': 6,
 'Ghost Rider': 7,
 'Hulk': 8,
 'Iron Man': 9,
 'Spiderman': 10,
 'Superman': 11}

### Checking the files in test folder 

In [39]:
import os

path, dirs, files = next(os.walk("data/test_images/CAX_Superhero_Test"))
file_count = len(files)
file_count

3376

### Creating dataframe to store output for test folder

In [2]:
df= pd.DataFrame(columns=['filename','Superhero'])

### prediction

In [42]:
i=0
for img in os.listdir('data/test_images/CAX_Superhero_Test'):
    print(img)
    if img != '.DS_Store':
        test_image = image.load_img('data/test_images/CAX_Superhero_Test/'+str(img), target_size = (64, 64))
        test_image = image.img_to_array(test_image)
        test_image = np.expand_dims(test_image, axis = 0)
        result = classifier.predict(test_image)
        print(result)
        for ind,x in enumerate(np.nditer(result)):
            if x==1.0:
                prediction = list(training_set.class_indices.keys())[list(training_set.class_indices.values()).index(ind)]
        df.loc[i] = [img,prediction]
        i+=1
        print(prediction)

print (i)

superhero_test_1310.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_3072.jpg
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Ant-Man
superhero_test_1434.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_95.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_2994.jpg
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
Black Panther
superhero_test_1688.jpg
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Aquaman
superhero_test_179.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_217.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_458.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_1373.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_377.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_3360.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_867.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_241.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_2381.jpg
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Captain America
superhero_test_1774.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_3352.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_1001.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_588.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
Hulk
superhero_test_3336.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_2564.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_2173.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_1458.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_1365.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_32.jpg
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Ant-Man
superhero_test_2662.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_25.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
Hulk
superher

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_2839.jpg
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Aquaman
superhero_test_2114.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_2170.jpg
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Aquaman
superhero_test_2059.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_2725.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_2434.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_2459.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_2336.jpg
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Ant-Man
superhero_test_321.jpg
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Avengers
superhero_test_1045.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_3031.jpg
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Avengers
superhero_test_2871.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_2201.jpg
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Avengers
superhero

[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
Hulk
superhero_test_559.jpg
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Aquaman
superhero_test_2407.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_1946.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_3292.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_147.jpg
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Avengers
superhero_test_178.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_319.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_1796.jpg
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Aquaman
superhero_test_1787.jpg
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 1.0679199e-21
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00
  0.0000000e+00 0.0000000e+00]]
Iron Man
superhero_test_181.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_564.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_460.jpg
[[0. 0

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_1126.jpg
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Captain America
superhero_test_2298.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_2330.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_2219.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_1259.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_1531.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_1877.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_2975.jpg
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00 2.4230041e-18
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00]]
Batman
superhero_test_3236.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_507.jpg
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
Black Panther
superhero_test_2453.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_t

superhero_test_1816.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_2159.jpg
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Avengers
superhero_test_656.jpg
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Avengers
superhero_test_3150.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_1857.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_615.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_2280.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_1105.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_254.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_2742.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_1738.jpg
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 9.9999154e-01 8.4742760e-06
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00]]
Batman
superhero_test_2376.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batm

[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
Hulk
superhero_test_232.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_3172.jpg
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Avengers
superhero_test_3227.jpg
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Avengers
superhero_test_1552.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_1074.jpg
[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
Catwoman
superhero_test_98.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
Hulk
superhero_test_3161.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_2903.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_2710.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_91.jpg
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Avengers
superhero_test_2052.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_2452.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_983.jpg
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
Ghost Rider
superhero_test_2

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Ant-Man
superhero_test_11.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_957.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_2018.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_2948.jpg
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Avengers
superhero_test_2969.jpg
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Aquaman
superhero_test_2782.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_1495.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_821.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_2326.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_715.jpg
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Aquaman
superhero_test_1070.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_1081.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_2171.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_tes

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_176.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_2790.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_679.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_188.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_1189.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_66.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_694.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_2998.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_114.jpg
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Avengers
superhero_test_462.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_796.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_1235.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_2919.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_2

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_2132.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_1438.jpg
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Ant-Man
superhero_test_477.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_1096.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
.DS_Store
superhero_test_2670.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_2002.jpg
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
Black Panther
superhero_test_2344.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_485.jpg
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
Black Panther
superhero_test_153.jpg
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
Black Panther
superhero_test_1299.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_1798.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_1859.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_2961.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_488.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_1625.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_1783.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_177.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_1945.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_2534.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_1409.jpg
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Aquaman
superhero_test_2678.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_174.jpg
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 1.3488608e-20
  0.0000000e+00 0.0000000e+00]]
Batman
superhero_test_3078.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_640.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_1545.jpg
[

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_1994.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_2788.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_2249.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_1336.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_3356.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_2590.jpg
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Captain America
superhero_test_2209.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_157.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_1962.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_1021.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_298.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_342.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_64.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_2228.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_306.jpg
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
Black Panther
superhero_test_703.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_750.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_2553.jpg
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Aquaman
superhero_test_49.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_3374.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_1360.jpg
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00 4.1624017e-11]]
Aquaman
superhero_test_2100.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_2229.jpg
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Captain America
superhero_test_2124.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_1193.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
Hulk
superhero_test_2858.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_849.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_2600.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_1450.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_2319.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_2945.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_2762.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_2895.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_658.jpg
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Captain America
superhero_test_2606.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_2287.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_3300.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhe

[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
Hulk
superhero_test_2368.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
Hulk
superhero_test_3266.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_1415.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_1213.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_2625.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_3035.jpg
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Captain America
superhero_test_6.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_3350.jpg
[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
Catwoman
superhero_test_2107.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_3030.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_955.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_729.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_820.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_96

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_674.jpg
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Avengers
superhero_test_3351.jpg
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Avengers
superhero_test_933.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_645.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_1818.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_2829.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_619.jpg
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Captain America
superhero_test_2619.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_1468.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_779.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_2008.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_2301.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_2311.jpg
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Captai

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_1271.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_2675.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_1808.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_1843.jpg
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Ant-Man
superhero_test_256.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_3368.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_294.jpg
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Aquaman
superhero_test_523.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_998.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_93.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_1734.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_1978.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_2628.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
Hulk
superhero_t

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_438.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
Hulk
superhero_test_3178.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_3362.jpg
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Captain America
superhero_test_841.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_1579.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_720.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_132.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_1426.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_3334.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
Hulk
superhero_test_1769.jpg
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Avengers
superhero_test_2623.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_990.jpg
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Aquaman
superhero_test_107.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_247

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Captain America
superhero_test_709.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_3259.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_139.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_921.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_1641.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_1120.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_3128.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_596.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_1573.jpg
[[0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 5.994793e-27 0.000000e+00 1.000000e+00
  0.000000e+00 0.000000e+00]]
Iron Man
superhero_test_2404.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_1030.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_716.jpg


Batman
superhero_test_2411.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_765.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_2813.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_17.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_2555.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_308.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_1537.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_229.jpg
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Aquaman
superhero_test_1562.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_3197.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_3235.jpg
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Aquaman
superhero_test_2481.jpg
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Captain America
superhero_test_2424.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_2186.jpg
[[0. 0. 0. 0. 0. 0. 0. 0.

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_3146.jpg
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Avengers
superhero_test_2101.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_2165.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_2299.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_889.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_1621.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_2733.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_2849.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_2009.jpg
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Captain America
superhero_test_2385.jpg
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Captain America
superhero_test_2350.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_778.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_2737.jpg
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Cap

Superman
superhero_test_1726.jpg
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Captain America
superhero_test_1119.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_4.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_1556.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_3090.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_606.jpg
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Captain America
superhero_test_2464.jpg
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Aquaman
superhero_test_1427.jpg
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Captain America
superhero_test_3353.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_1026.jpg
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Captain America
superhero_test_352.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_2305.jpg
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Avengers
superhero_test_1469.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_2527.jpg


Captain America
superhero_test_401.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_3154.jpg
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Captain America
superhero_test_2242.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_3002.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_3241.jpg
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Captain America
superhero_test_2947.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
Hulk
superhero_test_399.jpg
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Captain America
superhero_test_1629.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_2065.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_2626.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_2825.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_283.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_3099.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_2004.j

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_3001.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_2262.jpg
[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
Catwoman
superhero_test_1694.jpg
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
Black Panther
superhero_test_2973.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_571.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_414.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_3147.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_224.jpg
[[0.000000e+00 0.000000e+00 5.378877e-23 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 1.000000e+00
  0.000000e+00 0.000000e+00]]
Iron Man
superhero_test_1475.jpg
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Captain America
superhero_test_1113.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
Hulk
superhero_test_2013.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_1404.jpg


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_1752.jpg
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Ant-Man
superhero_test_245.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_3039.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_2090.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_2032.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_325.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_1011.jpg
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Ant-Man
superhero_test_227.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_2770.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_3008.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_2890.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_876.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_541.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_2

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Aquaman
superhero_test_3139.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_2487.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_2650.jpg
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Ant-Man
superhero_test_865.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_1148.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_573.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_2880.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_1926.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_2647.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_2480.jpg
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Captain America
superhero_test_672.jpg
[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
Catwoman
superhero_test_2554.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_1737.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
super

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Captain America
superhero_test_3363.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_3075.jpg
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Avengers
superhero_test_2776.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_1306.jpg
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
Black Panther
superhero_test_3196.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
Hulk
superhero_test_472.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_2777.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_413.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_1293.jpg
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Aquaman
superhero_test_452.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_2588.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_2302.jpg
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Aquaman
superhero_test_3069.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
supe

Batman
superhero_test_856.jpg
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Aquaman
superhero_test_2812.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Superman
superhero_test_1401.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_1135.jpg
[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
Catwoman
superhero_test_2069.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_1707.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_2497.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Spiderman
superhero_test_2174.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
Hulk
superhero_test_1176.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_270.jpg
[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
Catwoman
superhero_test_1782.jpg
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Batman
superhero_test_2891.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_647.jpg
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Captain America
superhero_test_3332.jpg
[[0.0000000e+00 0.0000000e

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Aquaman
superhero_test_3245.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_825.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
superhero_test_2492.jpg
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Iron Man
3375


In [43]:
df

filename        Superhero
0     superhero_test_1310.jpg         Iron Man
1     superhero_test_3072.jpg          Ant-Man
2     superhero_test_1434.jpg           Batman
3       superhero_test_95.jpg           Batman
4     superhero_test_2994.jpg    Black Panther
5     superhero_test_1688.jpg          Aquaman
6      superhero_test_179.jpg        Spiderman
7      superhero_test_217.jpg         Iron Man
8      superhero_test_458.jpg         Superman
9     superhero_test_1373.jpg        Spiderman
10     superhero_test_377.jpg           Batman
11    superhero_test_3360.jpg        Spiderman
12     superhero_test_867.jpg           Batman
13     superhero_test_241.jpg         Superman
14    superhero_test_2567.jpg         Superman
15    superhero_test_1407.jpg         Iron Man
16     superhero_test_359.jpg    Black Panther
17    superhero_test_2231.jpg        Spiderman
18     superhero_test_982.jpg         Avengers
19    superhero_test_1913.jpg         Superman
20    superhero_test_1273.jpg          Ant-Man
21    superhero_test_2995.jpg           Batman
22    superhero_test_2659.jpg        Spiderman
23    superhero_test_2045.jpg  Captain America
24    superhero_test_1320.jpg  Captain America
25     superhero_test_780.jpg         Iron Man
26      superhero_test_45.jpg  Captain America
27    superhero_test_1361.jpg           Batman
28    superhero_test_3296.jpg          Ant-Man
29    superhero_test_1101.jpg           Batman
...                       ...              ...
3345    superhero_test_67.jpg        Spiderman
3346  superhero_test_2706.jpg         Iron Man
3347  superhero_test_1035.jpg           Batman
3348  superhero_test_1130.jpg  Captain America
3349  superhero_test_1244.jpg           Batman
3350   superhero_test_528.jpg  Captain America
3351  superhero_test_2724.jpg         Superman
3352  superhero_test_2491.jpg         Avengers
3353   superhero_test_568.jpg         Avengers
3354   superhero_test_587.jpg         Iron Man
3355  superhero_test_2446.jpg           Batman
3356  superhero_test_2869.jpg         Iron Man
3357  superhero_test_1499.jpg      Ghost Rider
3358  superhero_test_2597.jpg         Iron Man
3359    superhero_test_97.jpg        Spiderman
3360   superhero_test_194.jpg         Superman
3361  superhero_test_1591.jpg         Iron Man
3362   superhero_test_853.jpg        Spiderman
3363   superhero_test_200.jpg         Superman
3364  superhero_test_2022.jpg         Iron Man
3365  superhero_test_2188.jpg        Spiderman
3366  superhero_test_2918.jpg           Batman
3367  superhero_test_2067.jpg         Superman
3368  superhero_test_1038.jpg         Superman
3369   superhero_test_915.jpg             Hulk
3370  superhero_test_3047.jpg         Iron Man
3371  superhero_test_2634.jpg          Aquaman
3372  superhero_test_3245.jpg         Iron Man
3373   superhero_test_825.jpg         Iron Man
3374  superhero_test_2492.jpg         Iron Man

[3375 rows x 2 columns]

### saving into a csv file 

In [44]:
df.to_csv('Superhero_3375_SampleSubmission.csv',sep=',',index=False)